---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.gunicorn default variables [[[
# =====================================

# .. contents:: Sections
#    :local:
#
# .. include:: includes/all.rst


# APT packages [[[
# ----------------

# .. envvar:: gunicorn__base_packages [[[
#
# The essential packages to install for gunicorn support.
gunicorn__base_packages: [ 'gunicorn', 'python-setproctitle' ]

                                                                   # ]]]
# .. envvar:: gunicorn__packages [[[
#
# Additional APT packages to install with gunicorn.
gunicorn__packages: []
                                                                   # ]]]
                                                                   # ]]]
# Managed applications [[[
# ------------------------

# .. envvar:: gunicorn__applications [[[
#
# List of WSGI applications which are managed by the role, defined in the
# Ansible inventory. See :ref:`gunicorn__ref_applications` for more details.
gunicorn__applications: []

                                                                   # ]]]
# .. envvar:: gunicorn__dependent_applications [[[
#
# List of WSGI applications which are managed by the role, defined by other
# Ansible roles using dependent variables.
# See :ref:`gunicorn__ref_applications` for more details.
gunicorn__dependent_applications: []
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
