---

- name: Manage Green Unicorn service
  hosts: [ 'debops_service_gunicorn' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.gunicorn
      tags: [ 'role::gunicorn' ]
