---
galaxy_info:
  author: Vlad Dem
  description: Install Nginx
  license: MIT
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - system
