---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/gunicorn"
  github_url: "https://github.com/debops/ansible-gunicorn"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'


  synopsis: |
    The [Green Unicorn](http://gunicorn.org/) is a Python WSGI HTTP Server for
    UNIX. It uses a pre-fork worker model ported from Ruby's Unicorn project. The
    Gunicorn server is broadly compatible with various web frameworks, simply
    implemented, light on server resources, and fairly speedy.
    
    The `debops.gunicorn` Ansible role uses the [Debian package configuration structure](https://chris-lamb.co.uk/posts/sysadmin-friendly-deployment-gunicorn-debian)
    to manage multiple `gunicorn` applications as a signle service. This can be
    used to deploy applications that use either a system Python installation, or
    a `virtualenv` Python environment.
